worker_processes                auto;
error_log                       /var/log/nginx/error.log warn;

events {
    worker_connections          1024;
}

http {
    server {
        listen                  80;
        server_name             localhost;
        client_max_body_size    32m;
        location /back {
            proxy_pass          http://meu-back:3001;
        }
        #https://www.mongodb.com/pt-br/docs/manual/reference/default-mongodb-port/
        # Quando startar
        location /database{
            proxy_pass          http://meu-banco:27017;
        }
    }
}